// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXi_gRQomKTGxyXN8_upakr42a5tfdvb8',
    appId: '1:302423523968:web:b2ad503b372d01fde15c65',
    messagingSenderId: '302423523968',
    projectId: 'mds-m2-flutter-exotik-ecom',
    authDomain: 'mds-m2-flutter-exotik-ecom.firebaseapp.com',
    storageBucket: 'mds-m2-flutter-exotik-ecom.firebasestorage.app',
    measurementId: 'G-XBMEP0G6WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLJI8LJdzBxcYjVfoblOnYT19oixq1uz4',
    appId: '1:302423523968:android:7ab0be06dc7a9baee15c65',
    messagingSenderId: '302423523968',
    projectId: 'mds-m2-flutter-exotik-ecom',
    storageBucket: 'mds-m2-flutter-exotik-ecom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2_ai72P0W2CNknOV2hyT59j6Y1Myi6lo',
    appId: '1:302423523968:ios:8e62072dbf71987ee15c65',
    messagingSenderId: '302423523968',
    projectId: 'mds-m2-flutter-exotik-ecom',
    storageBucket: 'mds-m2-flutter-exotik-ecom.firebasestorage.app',
    iosBundleId: 'com.example.flutterEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2_ai72P0W2CNknOV2hyT59j6Y1Myi6lo',
    appId: '1:302423523968:ios:8e62072dbf71987ee15c65',
    messagingSenderId: '302423523968',
    projectId: 'mds-m2-flutter-exotik-ecom',
    storageBucket: 'mds-m2-flutter-exotik-ecom.firebasestorage.app',
    iosBundleId: 'com.example.flutterEcommerce',
  );
}
