
name: Deploy to Firebase Hosting on PR
on:
  workflow_run:
    workflows: ['CI']
    branches:
      - main
    types:
      - completed

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download web build artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: build/web

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MDS_M2_FLUTTER_EXOTIK_ECOM }}
          projectId: mds-m2-flutter-exotik-ecom
